# Generated by Django 5.1.6 on 2026-06-03 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero_economico', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número económico')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('correo_institucional', models.EmailField(max_length=254, unique=True, verbose_name='Correo institucional')),
                ('usuario', models.OneToOneField(limit_choices_to={'rol': 'PROFESOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profesor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
