# Generated by Django 5.1.6 on 2026-06-03 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profesor'),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesores', to='catalogos.departamento'),
        ),
    ]
