# Generated by Django 5.1.6 on 2026-06-03 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('clave', models.CharField(max_length=20, unique=True, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('clave', models.CharField(max_length=10, unique=True, verbose_name='Clave')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('activo', models.BooleanField(default=False, verbose_name='Periodo activo')),
                ('estado', models.BooleanField(default=True, verbose_name='Habilitado')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('clave', models.CharField(max_length=20, unique=True, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenciaturas', to='catalogos.departamento')),
            ],
            options={
                'verbose_name': 'Licenciatura',
                'verbose_name_plural': 'Licenciaturas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UEA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('clave', models.CharField(max_length=20, unique=True, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
                ('trimestre', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Trimestre')),
                ('etapa', models.CharField(blank=True, choices=[('TG', 'Tronco General'), ('TB', 'Tronco Básico Profesional'), ('TI', 'Tronco de Integración')], max_length=4, verbose_name='Etapa formativa')),
                ('tipo', models.CharField(choices=[('OBL', 'Obligatoria'), ('OPT', 'Optativa'), ('OTRO', 'Otro')], default='OBL', max_length=4, verbose_name='Tipo')),
                ('creditos', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Créditos')),
                ('licenciatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ueas', to='catalogos.licenciatura')),
            ],
            options={
                'verbose_name': 'UEA',
                'verbose_name_plural': 'UEA',
                'ordering': ['licenciatura', 'trimestre', 'nombre'],
            },
        ),
    ]
