# Generated by Django 5.1.6 on 2026-06-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_periodo_por_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='uea',
            name='liga',
            field=models.URLField(blank=True, max_length=500, verbose_name='Liga / página oficial'),
        ),
    ]
