# Generated by Django 5.1.6 on 2026-06-09 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_uea_liga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licenciatura',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Licenciatura', 'verbose_name_plural': 'Licenciaturas'},
        ),
        migrations.RemoveField(
            model_name='uea',
            name='etapa',
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='orden',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='uea',
            name='trimestre',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Trimestre'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['nombre', 'descripcion'],
                'unique_together': {('nombre', 'descripcion')},
            },
        ),
        migrations.AddField(
            model_name='uea',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ueas', to='catalogos.area'),
        ),
    ]
