# Generated by Django 5.1.6 on 2026-06-15 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_rename_dps_to_dips'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uea',
            options={'ordering': ['licenciatura', 'posgrado', 'trimestre', 'nombre'], 'verbose_name': 'UEA', 'verbose_name_plural': 'UEA'},
        ),
        migrations.AlterField(
            model_name='uea',
            name='licenciatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ueas', to='catalogos.licenciatura'),
        ),
        migrations.CreateModel(
            name='Posgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('clave', models.CharField(max_length=20, unique=True, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posgrados', to='catalogos.departamento')),
            ],
            options={
                'verbose_name': 'Posgrado',
                'verbose_name_plural': 'Posgrados',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='uea',
            name='posgrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ueas', to='catalogos.posgrado'),
        ),
        migrations.AddConstraint(
            model_name='uea',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('licenciatura__isnull', False), ('posgrado__isnull', True)), models.Q(('licenciatura__isnull', True), ('posgrado__isnull', False)), _connector='OR'), name='uea_xor_licenciatura_posgrado'),
        ),
    ]
