# Generated by Django 5.1.6 on 2026-07-26 02:43

from django.db import migrations, models


def normalizar_claves(apps, schema_editor):
    """Uppercase de `clave` en registros existentes antes de aplicar las
    UniqueConstraint case-sensitive por programa."""
    UEA = apps.get_model('catalogos', 'UEA')
    for uea in UEA.objects.all():
        normalizada = uea.clave.strip().upper()
        if normalizada != uea.clave:
            uea.clave = normalizada
            uea.save(update_fields=['clave'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_uea_options_alter_uea_licenciatura_posgrado_and_more'),
    ]

    operations = [
        migrations.RunPython(normalizar_claves, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='uea',
            name='clave',
            field=models.CharField(max_length=20, verbose_name='Clave'),
        ),
        migrations.AddConstraint(
            model_name='uea',
            constraint=models.UniqueConstraint(condition=models.Q(('licenciatura__isnull', False)), fields=('clave', 'licenciatura'), name='uea_clave_unica_por_licenciatura'),
        ),
        migrations.AddConstraint(
            model_name='uea',
            constraint=models.UniqueConstraint(condition=models.Q(('posgrado__isnull', False)), fields=('clave', 'posgrado'), name='uea_clave_unica_por_posgrado'),
        ),
    ]
