# Generated by Django 5.1.6 on 2026-06-03 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profesor_departamento'),
        ('autoevaluacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelDesempeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('porcentaje_min', models.DecimalField(decimal_places=2, help_text='Porcentaje mínimo (0–100) para este nivel.', max_digits=5, verbose_name='% mínimo')),
                ('porcentaje_max', models.DecimalField(decimal_places=2, help_text='Porcentaje máximo (0–100) para este nivel.', max_digits=5, verbose_name='% máximo')),
                ('observacion', models.TextField(verbose_name='Observación')),
                ('color', models.CharField(default='gray', help_text='Clave para la UI: green | blue | yellow | red | gray', max_length=20, verbose_name='Color')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Nivel de desempeño',
                'verbose_name_plural': 'Niveles de desempeño',
                'ordering': ['orden', 'porcentaje_min'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='respuesta',
            name='unique_respuesta_formulario_profesor',
        ),
        migrations.AddField(
            model_name='formulario',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Versión'),
        ),
        migrations.AddField(
            model_name='opcionpregunta',
            name='puntos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Puntos'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje (%)'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='puntaje_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Puntaje máximo posible'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='puntaje_obtenido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Puntaje obtenido'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='version_formulario',
            field=models.PositiveIntegerField(default=1, verbose_name='Versión del formulario'),
        ),
        migrations.AddField(
            model_name='niveldesempeno',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='autoevaluacion.formulario', verbose_name='Formulario'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='nivel_desempeno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='autoevaluacion.niveldesempeno', verbose_name='Nivel de desempeño'),
        ),
        migrations.AddConstraint(
            model_name='respuesta',
            constraint=models.UniqueConstraint(fields=('formulario', 'profesor', 'version_formulario'), name='unique_respuesta_formulario_profesor_version'),
        ),
    ]
