# Generated by Django 5.1.6 on 2026-06-18 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoevaluacion', '0003_seccion_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('TEXTO_CORTO', 'Texto corto'), ('TEXTO_LARGO', 'Texto largo'), ('OPCION_UNICA', 'Opción única'), ('CASILLAS', 'Casillas de verificación'), ('SI_NO', 'Sí / No'), ('ESCALA_LINEAL', 'Escala lineal'), ('LISTA_DESPLEGABLE', 'Lista desplegable'), ('CUADRICULA', 'Cuadrícula de opciones')], max_length=20),
        ),
        migrations.CreateModel(
            name='FilaCuadricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255, verbose_name='Texto de la fila')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='autoevaluacion.pregunta')),
            ],
            options={
                'verbose_name': 'Fila de cuadrícula',
                'verbose_name_plural': 'Filas de cuadrícula',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaCelda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='autoevaluacion.filacuadricula')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='autoevaluacion.opcionpregunta')),
                ('respuesta_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celdas', to='autoevaluacion.respuestapregunta')),
            ],
            options={
                'verbose_name': 'Celda de respuesta',
                'verbose_name_plural': 'Celdas de respuesta',
                'unique_together': {('respuesta_pregunta', 'fila')},
            },
        ),
    ]
