# Generated by Django 5.1.6 on 2026-06-18 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoevaluacion', '0004_cuadricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (%)')),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, max_digits=7)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje (%)')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones_resultado', to='autoevaluacion.respuesta')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='autoevaluacion.seccion')),
            ],
            options={
                'verbose_name': 'Resultado de sección',
                'verbose_name_plural': 'Resultados de sección',
                'unique_together': {('respuesta', 'seccion')},
            },
        ),
    ]
