# Generated by Django 5.1.6 on 2026-06-03 01:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_profesor_departamento'),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaTematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre_grupo', models.CharField(max_length=100, verbose_name='Nombre del grupo')),
                ('id_grupo', models.CharField(max_length=50, verbose_name='ID del grupo')),
                ('horario', models.CharField(max_length=100, verbose_name='Horario')),
                ('modalidad', models.CharField(blank=True, choices=[('PRESENCIAL', 'Presencial'), ('REMOTO', 'Remoto'), ('MIXTO', 'Mixto')], max_length=12, verbose_name='Modalidad')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('ENVIADO', 'Enviado')], default='BORRADOR', max_length=10, verbose_name='Estado')),
                ('objetivo_general', models.TextField(blank=True, verbose_name='Objetivo general')),
                ('presentacion', models.TextField(blank=True, verbose_name='Presentación')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='catalogos.periodo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.profesor')),
                ('uea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='catalogos.uea')),
            ],
            options={
                'verbose_name': 'Carta Temática',
                'verbose_name_plural': 'Cartas Temáticas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bibliografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BASICA', 'Básica'), ('COMPLEMENTARIA', 'Complementaria')], default='BASICA', max_length=15, verbose_name='Tipo')),
                ('referencia', models.TextField(verbose_name='Referencia')),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bibliografias', to='documentos.cartatematica')),
            ],
            options={
                'ordering': ['tipo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('ponderacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Ponderación (%)')),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='documentos.cartatematica')),
            ],
            options={
                'ordering': ['-ponderacion'],
            },
        ),
        migrations.CreateModel(
            name='RequisitoRecuperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('nombre_grupo', models.CharField(max_length=100, verbose_name='Nombre del grupo')),
                ('id_grupo', models.CharField(max_length=50, verbose_name='ID del grupo')),
                ('horario', models.CharField(max_length=100, verbose_name='Horario')),
                ('modalidad', models.CharField(blank=True, choices=[('PRESENCIAL', 'Presencial'), ('REMOTO', 'Remoto'), ('MIXTO', 'Mixto')], max_length=12, verbose_name='Modalidad')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('ENVIADO', 'Enviado')], default='BORRADOR', max_length=10, verbose_name='Estado')),
                ('espacio_modalidad', models.CharField(blank=True, choices=[('PRESENCIAL', 'Presencial'), ('REMOTO', 'Remoto'), ('MIXTO', 'Mixto')], max_length=12, verbose_name='Espacio / Modalidad')),
                ('indicaciones', models.TextField(blank=True, verbose_name='Indicaciones de recuperación')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='catalogos.periodo')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='accounts.profesor')),
                ('uea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='catalogos.uea')),
            ],
            options={
                'verbose_name': 'Requisito de Recuperación',
                'verbose_name_plural': 'Requisitos de Recuperación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documentos.requisitorecuperacion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre del tema')),
                ('objetivo', models.TextField(blank=True, verbose_name='Objetivo del tema')),
                ('num_sesiones', models.PositiveSmallIntegerField(default=1, verbose_name='Número de sesiones')),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='documentos.cartatematica')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Subtema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='Orden')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtemas', to='documentos.tema')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddConstraint(
            model_name='cartatematica',
            constraint=models.UniqueConstraint(fields=('profesor', 'periodo', 'uea', 'id_grupo'), name='unique_carta_profesor_periodo_uea_grupo'),
        ),
        migrations.AddConstraint(
            model_name='requisitorecuperacion',
            constraint=models.UniqueConstraint(fields=('profesor', 'periodo', 'uea', 'id_grupo'), name='unique_requisito_profesor_periodo_uea_grupo'),
        ),
    ]
