# Generated by Django 5.1.6 on 2026-06-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterioevaluacion',
            name='carta',
        ),
        migrations.RemoveField(
            model_name='requisitoitem',
            name='requisito',
        ),
        migrations.RemoveField(
            model_name='subtema',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='carta',
        ),
        migrations.RemoveField(
            model_name='cartatematica',
            name='presentacion',
        ),
        migrations.RemoveField(
            model_name='requisitorecuperacion',
            name='espacio_modalidad',
        ),
        migrations.RemoveField(
            model_name='requisitorecuperacion',
            name='indicaciones',
        ),
        migrations.AddField(
            model_name='cartatematica',
            name='bibliografia',
            field=models.TextField(blank=True, verbose_name='Bibliografía'),
        ),
        migrations.AddField(
            model_name='cartatematica',
            name='calendarizacion_actividades',
            field=models.TextField(blank=True, verbose_name='Calendarización de actividades'),
        ),
        migrations.AddField(
            model_name='cartatematica',
            name='conocimientos_previos',
            field=models.TextField(blank=True, verbose_name='Conocimientos previos'),
        ),
        migrations.AddField(
            model_name='cartatematica',
            name='contenido_sintetico',
            field=models.TextField(blank=True, verbose_name='Contenido sintético'),
        ),
        migrations.AddField(
            model_name='cartatematica',
            name='descripcion_uea',
            field=models.TextField(blank=True, verbose_name='Descripción de la UEA'),
        ),
        migrations.AddField(
            model_name='cartatematica',
            name='modalidad_evaluacion',
            field=models.TextField(blank=True, verbose_name='Modalidad de evaluación'),
        ),
        migrations.AddField(
            model_name='cartatematica',
            name='objetivos_aprendizaje',
            field=models.TextField(blank=True, verbose_name='Objetivos de aprendizaje'),
        ),
        migrations.AddField(
            model_name='cartatematica',
            name='objetivos_particulares',
            field=models.TextField(blank=True, verbose_name='Objetivos particulares'),
        ),
        migrations.AddField(
            model_name='cartatematica',
            name='requerimientos',
            field=models.TextField(blank=True, help_text='Materiales y herramientas necesarios.', verbose_name='Requerimientos'),
        ),
        migrations.AddField(
            model_name='cartatematica',
            name='revisiones_asesorias',
            field=models.TextField(blank=True, verbose_name='Revisiones / asesorías'),
        ),
        migrations.AddField(
            model_name='requisitorecuperacion',
            name='duracion_aprox',
            field=models.CharField(blank=True, max_length=100, verbose_name='Duración aproximada'),
        ),
        migrations.AddField(
            model_name='requisitorecuperacion',
            name='fecha_hora',
            field=models.CharField(blank=True, help_text="Texto libre, ej. 'Lunes 15 de mayo, 10:00 h'.", max_length=100, verbose_name='Fecha y hora'),
        ),
        migrations.AddField(
            model_name='requisitorecuperacion',
            name='lugar',
            field=models.TextField(blank=True, help_text='Texto libre. Si es remoto, puede incluir liga y contraseña.', verbose_name='Lugar'),
        ),
        migrations.AddField(
            model_name='requisitorecuperacion',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='requisitorecuperacion',
            name='recursos_necesarios',
            field=models.TextField(blank=True, help_text='Materiales, herramientas, etc.', verbose_name='Recursos necesarios'),
        ),
        migrations.AddField(
            model_name='requisitorecuperacion',
            name='requisitos',
            field=models.TextField(blank=True, help_text='Investigación, maqueta, % de tareas entregadas, etc.', verbose_name='Requisitos'),
        ),
        migrations.DeleteModel(
            name='Bibliografia',
        ),
        migrations.DeleteModel(
            name='CriterioEvaluacion',
        ),
        migrations.DeleteModel(
            name='RequisitoItem',
        ),
        migrations.DeleteModel(
            name='Subtema',
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
    ]
