# Generated by Django 5.1.6 on 2026-06-07 05:44

import django.db.models.deletion
from django.db import migrations, models


def _backfill_snapshots(apps, schema_editor):
    """Copia el nombre/correo del profesor vigente a los snapshots de los
    documentos existentes, para que no queden vacíos cuando el FK se
    nullifique al eliminar un profesor."""
    CartaTematica = apps.get_model("documentos", "CartaTematica")
    RequisitoRecuperacion = apps.get_model("documentos", "RequisitoRecuperacion")
    for Modelo in (CartaTematica, RequisitoRecuperacion):
        for doc in Modelo.objects.select_related("profesor").all():
            if not doc.profesor_id:
                continue
            doc.profesor_nombre = doc.profesor.nombre_completo or ""
            doc.profesor_correo = doc.profesor.correo_institucional or ""
            doc.save(update_fields=["profesor_nombre", "profesor_correo"])


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profesor_departamento'),
        ('documentos', '0003_retirar_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartatematica',
            name='profesor_correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo del profesor (histórico)'),
        ),
        migrations.AddField(
            model_name='cartatematica',
            name='profesor_nombre',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del profesor (histórico)'),
        ),
        migrations.AddField(
            model_name='requisitorecuperacion',
            name='profesor_correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo del profesor (histórico)'),
        ),
        migrations.AddField(
            model_name='requisitorecuperacion',
            name='profesor_nombre',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre del profesor (histórico)'),
        ),
        # Backfill ANTES de cambiar el FK: aprovechamos que el profesor
        # actual aún está enlazado para copiar su nombre/correo.
        migrations.RunPython(_backfill_snapshots, _noop),
        migrations.AlterField(
            model_name='cartatematica',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='accounts.profesor'),
        ),
        migrations.AlterField(
            model_name='requisitorecuperacion',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='accounts.profesor'),
        ),
    ]
