# Generated by Django 5.1.6 on 2026-07-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_profesor_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartatematica',
            name='enlace',
            field=models.TextField(blank=True, help_text='Liga(s) para clases en línea o asesorías.', verbose_name='Enlace'),
        ),
    ]
